plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT" apply false
    id "dev.architectury.loom" version "1.13.467" apply false
}

subprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "dev.architectury.loom"
    apply plugin: "maven-publish"
    
    group = rootProject.maven_group
    version = rootProject.mod_version
    
    base {
        archivesName = "${rootProject.archives_base_name}-${project.name}"
    }
    
    repositories {
        mavenCentral()
    }
    
    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.officialMojangMappings()
    }
    
    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 21
    }
}
